# Generated by Django 5.2.5 on 2025-08-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='emai',
            new_name='email',
        ),
    ]
