# Generated by Django 5.2.5 on 2025-09-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tarefas_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='prioridade',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Media'), ('Alta', 'Alta')], default='B', max_length=5),
        ),
    ]
